### ISSUE TITLE
Error when starting hosting

### ISSUE THREAD

**Issue by iNightboat** [kamyu1537/WebFishingDedicatedServer#1]
When trying to start the server, a similar error pops up in the console: [log-20241116.txt](https://github.com/user-attachments/files/17787478/log-20241116.txt)
Since my knowledge of programming is not very great, I have no idea what exactly needs to be done to get rid of it.

**Comment by kamyu1537** [comment]
I think there was a problem while reading the map file. Can you provide me with information on which version you used and which map you used other than the basic map?

**Comment by iNightboat** [comment]
I used version 1.1.9 of the program, also checked for 1.1.8. The game client itself is modified via r2modman, but the game map is basic, unchanged.

**Comment by iNightboat** [comment]
I used version 1.1.9 of the program, also checked for 1.1.8.
The game client itself is modified via r2modman, but the game map is basic, unchanged.

**Comment by kamyu1537** [comment]
Now released version 1.1.10. Can you check this version?

**Comment by iNightboat** [comment]
Everything is working properly. Thank you so much for responding to my request and correcting the error!

**Comment by kamyu1537** [comment]
re-released version 1.1.11 due to map loading issues when connecting to the server. please update!
